### ISSUE TITLE
Erreur de génération de l'arbre lié aux identifiants des séquences 

### ISSUE THREAD

**Issue by NikaAb** [NikaAb/BCR_intraclonal_diversity#8]
Pour le fichier 907037, le regroupement clonal n'arrive pas à être fait. J'ai le message d'erreur suivant :

```
 File "GTM/two_level_clonal_info.py", line 145, in <module>
    main()
  File "GTM/two_level_clonal_info.py", line 139, in main
    clonal_info_dico,clonotype_dico = gather_clone_clonotype_info(dico_result,dico_vjunc,IMGT_seq_info)
  File "GTM/two_level_clonal_info.py", line 73, in gather_clone_clonotype_info
    if dicoSeq[s][3] in clonotypes[c].keys() :
KeyError: 'M03464:7:000000000-AC97E:1:1113:15319:8062'
```

    Pour le fichier 978980, il y a uniquement l'arbre à 30 clonotypes qui n'est pas généré, j'ai le message d'erreur suivant :

```
Traceback (most recent call last):
  File "select_clone/alignment_intraclonal.py", line 304, in <module>
    main()
  File "select_clone/alignment_intraclonal.py", line 299, in main
    write_clonotype_align(region_compered_to_germ,repertoire_name,coressp_dico,total_seq_clone,airr_df)
  File "select_clone/alignment_intraclonal.py", line 91, in write_clonotype_align
    G = "germline"+"\t"+"_"+"\t" + "_" + "\t" +region['germline'][0][0:region['germline'][1][0]]+"\t"+ region['germline'][0][region['germline'][1][0]:region['germline'][1][1]]+"\t"+ region['germline'][0][region['germline'][1][1]:region['germline'][1][2]]+"\t"+ region['germline'][0][region['germline'][1][2]:region['germline'][1][3]]+"\t"+ region['germline'][0][region['germline'][1][3]:region['germline'][1][4]]+"\t"+ region['germline'][0][region['germline'][1][4]:region['germline'][1][5]]+"\t"+ region['germline'][0][region['germline'][1][5]:region['germline'][1][6]]+"\t"+ region['germline'][0][region['germline'][1][6]:region['germline'][1][7]]+"\t"+ region['germline'][0][region['germline'][1][7]:-1]+"\n"
IndexError: list index out of range

et les deux arbres du clone C4 ne sont pas générés avec comme message d'erreur :
Traceback (most recent call last):
  File "select_clone/alignment_intraclonal.py", line 304, in <module>
    main()
  File "select_clone/alignment_intraclonal.py", line 299, in main
    write_clonotype_align(region_compered_to_germ,repertoire_name,coressp_dico,total_seq_clone,airr_df)
  File "select_clone/alignment_intraclonal.py", line 100, in write_clonotype_align
    clonotype_info = key+"\t"+str(len(coressp_dico[key])+1)+"("+str("%.5f" %percentage)+")"+ "\t"+ str(V_percent) + "\t" +region[key][0][0:region[key][1][0]]+"\t"+ region[key][0][region[key][1][0]:region[key][1][1]]+"\t"+ region[key][0][region[key][1][1]:region[key][1][2]]+"\t"+ region[key][0][region[key][1][2]:region[key][1][3]]+"\t"+ region[key][0][region[key][1][3]:region[key][1][4]]+"\t"+ region[key][0][region[key][1][4]:region[key][1][5]]+"\t"+ region[key][0][region[key][1][5]:region[key][1][6]]+"\t"+ region[key][0][region[key][1][6]:region[key][1][7]]+"\t"+ region[key][0][region[key][1][7]:-1]+"\n"
IndexError: list index out of range
Traceback (most recent call last):
  File "select_clone/alignment_intraclonal.py", line 304, in <module>
    main()
  File "select_clone/alignment_intraclonal.py", line 290, in main
    clonotype_seq,germline,list_selected_clonotype,sorted_based_on_V_identity_seq_id = read_seq_info(lines_clonotype_seq,airr_df,nb_clonotype)
  File "select_clone/alignment_intraclonal.py", line 62, in read_seq_info
    germline = airr_df.loc[airr_df['sequence_id'] == sorted_based_on_V_identity[-1][1]]["germline_seq"].values[0]
IndexError: list index out of range

Traceback (most recent call last):
  File "select_clone/alignment_intraclonal.py", line 304, in <module>
    main()
  File "select_clone/alignment_intraclonal.py", line 290, in main
    clonotype_seq,germline,list_selected_clonotype,sorted_based_on_V_identity_seq_id = read_seq_info(lines_clonotype_seq,airr_df,nb_clonotype)
  File "select_clone/alignment_intraclonal.py", line 62, in read_seq_info
    germline = airr_df.loc[airr_df['sequence_id'] == sorted_based_on_V_identity[-1][1]]["germline_seq"].values[0]
IndexError: list index out of range

```

**Comment by LucileJeusset** [comment]
@NikaAb J'ai ajouté un petit script qui modifie les identifiants de séquence. Cela permet de corriger le problème de regroupement clonal du fichier 907037. 
Pour la génération des arbres, j'ai remarqué qu'une des erreurs provient du fait que pour certains clonotypes les variables _d_sequence_end_ et _cdr3_end_ ont la même valeur. Après ajustement des régions par la fonction _column_from_residue_number_, on se retrouve avec 7 éléments au lieu de 8 dans la liste de la variable lim (_write_clonotype_align_seq_). Est-ce que, dans ce cas, je peux mettre deux valeurs identiques pour les variables _endD_ et _endCDR3_ ou cela va-t-il poser un problème pour le reste de l'analyse?

**Comment by NikaAb** [comment]
Ah merci beaucoup @LucileJeusset ! 
Hmmm ⊙︿⊙ C'est à dire sur cette séquence on n'a pas des nucléotide de région N an aval de gène D ?! Je ne sais pas si cela peut arriver biologiquement ou c'est un décalage de la position de D en raison d'alignement IMGT (le D est trop petit ou on retrouve un motif qui peut aussi représenter un D à la fin de CDR3). 
En tout cas, je pense qu'on peut mettre les deux identiques pour voir ce que ça donne. Avoir les mêmes valeurs, ne pose pas de problème pour l'affichage des séquences en alignement en bas de la page d’étude intraclonal?

**Comment by LucileJeusset** [comment]
Merci @NikaAb
Oui il n'y a pas de nucléotides de région N en aval du gène D. J'ai aussi remarqué en faisant les modifications que pour deux séquences il n'y a pas de nucléotides de région N en amont du gène D : j'ai les mêmes valeurs pour les variables _d_sequence_start_ et _cdr3_start_. Dans les deux cas j'ai mis les mêmes valeurs aux deux variables, je ne sais pas si ça va poser un problème au niveau biologique. 
Non ça ne pose pas de problème pour la visualisation.
Dans ce répertoire, il y a aussi un problème pour générer l'arbre du clone C4. J'ai une erreur dans la fonction _read_seq_info_ : aucunes séquences des clonotypes n'est retrouvées dans la variable _airr_df_. En effet toutes les séquences contenues dans le clone C4 sont supprimées du dataframe (fonction _read_AIRR_) car elles ne contiennent pas toutes les informations nécessaires pour le reste de l'analyse. Dans ce cas, on ne peut rien faire pour générer l'arbre? Est ce qu'il faut que j'indique quelque part la raison pour laquelle l'arbre n'a pas pu être généré?
